# Generated by Django 6.0.3 on 2026-03-12 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('session_type', models.CharField(choices=[('weights_tue', 'Pesas — Martes (Pull/Press)'), ('weights_sat', 'Pesas — Sábado (Piernas)'), ('weights_sun', 'Pesas — Domingo (Hombros/Brazos)'), ('football', 'Fútbol'), ('rest', 'Descanso')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FootballSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=True)),
                ('absence_reason', models.CharField(blank=True, choices=[('injury', 'Lesión'), ('work', 'Trabajo'), ('illness', 'Enfermedad'), ('travel', 'Viaje'), ('other', 'Otro')], max_length=20)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='football', to='workout.session')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('set_number', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workout.session')),
            ],
            options={
                'ordering': ['exercise_name', 'set_number'],
                'unique_together': {('session', 'exercise_name', 'set_number')},
            },
        ),
    ]
