# Generated by Django 6.0.3 on 2026-03-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cool_down_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='warm_up_done',
            field=models.BooleanField(default=False),
        ),
    ]
