# Generated by Django 6.0.3 on 2026-03-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_session_cool_down_done_session_warm_up_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('injury', 'Lesión'), ('work', 'Trabajo'), ('illness', 'Enfermedad'), ('travel', 'Viaje'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
